config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'documents#index'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/profile' => 'users#show', :as => :user 
  get '/profile/edit' => 'users#edit'
  patch '/profile' => 'users#update'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#open'
  delete '/logout' => 'sessions#close'

  resources :documents, except: [:new, :edit]
end

app/models/active_storage_table.rb
class ActiveStorageTable < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
    belongs_to :user
    has_one_attached :user_document
    validates :key, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :documents
    validates :user_name, :full_name, :email, presence: true
    validates :user_name, length: { maximum: 15 }, uniqueness: true
    validates :email, format: { with: URI::MailTo::EMAIL_REGEXP } 
    validates :password, presence: true, length: { minimum: 8, maximum: 15 }, on: :create
    validates :password, format: { 
            with: /(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).*/, 
            message:  "Password must contain atleast one uppercase, lowercase and number" 
        }, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :file_size_verbose

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    def require_user 
        redirect_to '/login' unless current_user 
    end 
    
    def file_size_verbose(byte)
        @kb = byte / 1024
        if @kb < 1024
            return "#{@kb} KB"
        end
        @mb = @kb / 1024
        if @mb < 1024
            return "#{@mb} MB"
        end
        @gb = @mb / 1024
        return "#{@gb} GB"
    end
end

app/controllers/documents_controller.rb
require 'securerandom'

class DocumentsController < ApplicationController
    before_action :require_user, except: [:show]

    def index
        @documents = current_user.documents.order(created_at: :desc)
    end

    def create
        current_user.documents.create(create_document_params)
        redirect_to '/'
    end

    def show
        @document = Document.find_by!(key: params[:id], shared: true)
        @user = User.find(@document[:user_id]) if @document
    end

    def update
        @checked = (params[:document] && (params[:document][:shared] == '1')) ? true : false
        @document = current_user.documents.find_by!(key: params[:id])
        @document && @document.update(shared: @checked) 
        redirect_to '/'
    end

    def destroy
        @document = current_user.documents.find_by!(key: params[:id])
        @document && @document.user_document.purge_later
        @document && @document.destroy
        redirect_to '/'
    end

    private
    def create_document_params
        params.require(:document).permit(:user_document).merge(key: "#{SecureRandom.hex(6)}#{Time.now.to_i}")
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        if session[:user_id]
            redirect_to '/' if User.find(session[:user_id])
        end
    end

    def open
        @params = params[:session]
        @user = User.find_by(user_name: @params[:user_name])
        puts @user
        puts @user[:password]
        if @user && @user[:password] == @params[:password]
            session[:user_id] = @user.id
            redirect_to '/'
        else
            render :new
        end 
    end

    def close
        session[:user_id] = nil 
        redirect_to '/login' 
    end
end

app/controllers/users_controller.rb
  
class UsersController < ApplicationController
    before_action :require_user, except: [:new, :create]
    def new
        if session[:user_id]
            redirect_to '/' if User.find(session[:user_id])
        else
            @user = User.new
        end
    end
    
    def create
        puts user_params
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to '/' 
        else
            render :new
        end
    end

    def show
        @user = current_user
    end

    def edit
        @user = current_user
    end

    def update
        @user = User.find(session[:user_id])
        if @user.update(user_params) 
            @profile_updated = true
            render :show
        else
            render :edit
        end
    end
    
    private
    def user_params
        params.require(:user).permit(:user_name, :full_name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/documents/index.html.erb
<div class="container">
    <div class="table-wrapper">
        <div class="table-title">
            <div class="row">
                <div class="col-sm-9">
                    <h2>
                        Dashboard <b>
                            <%= @documents.count %> File(s)
                        </b>
                    </h2>
                </div>
                <div class="col-sm-3">
                    <%= form_for(:document, url: documents_path, method: 'post') do |f| %>
                            <div class="custom-file add-new">
                            <%= f.label :user_document, class:"custom-file-label" do %>Upload File
                                <%= f.file_field :user_document, class: 'custom-file-input', 
                                    onchange: "this.form.submit();" %>
                            <% end %>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
        <% if @documents.any? %>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Uploaded Date (UTC)</th>
                        <th>Size</th>
                        <th>Actions</th>
                        <th>Share</th>
                    </tr>
                </thead>
                <tbody>
                    <% @documents.each do |document| %>
                        <% if document.user_document.attached? %>
                            <tr>
                                <td><%= document.user_document.filename %></td>
                                <td><%= document.user_document.created_at.strftime("%-d %b %Y %H:%M") %></td>
                                <td><%= file_size_verbose document.user_document.byte_size %></td>
                                <td>
                                    <%= link_to 'Download', document.user_document, download: '' %> |&nbsp;
                                    <%= link_to "Delete", document_path(document.key),
                                        data: {:confirm => 'Are you sure you want to delete?'}, 
                                        method: :delete %>
                                </td>
                                <td>
                                    <div>
                                        <%= form_for(:document, url: document_path(document.key), 
                                            method: 'patch') do |f| %>
                                            <div class="custom-control custom-switch">
                                                <input class="custom-control-input" type="checkbox" 
                                                    onclick="this.form.submit();" value="1" <%= 'checked' if document.shared %>
                                                    name="document[shared]" id="share-<%= document.key %>"/>
                                                <label class="custom-control-label" 
                                                    for="share-<%= document.key %>"></label>
                                            </div>
                                        <% end %>
                                        <% if document.shared %>
                                            <%= link_to "Link", document_path(document.key), target: :_blank %>
                                    <% end %>
                                    </div>
                                </td>
                            </tr>
                        <% end %>
                    <% end %>
                </tbody>
            </table>
        <% end %>
    </div>
</div>    

app/views/documents/show.html.erb
<div class="container">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-8">
                        <h2>
                            <% if @user %>
                                File shared by <b><%= @user.full_name %></b>
                            <% else %>
                                File not available
                            <% end %>
                        </h2>
                    </div>
                </div>
            </div>
            <% if @document %>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Uploaded Date (UTC)</th>
                            <th>Size</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><%= @document.user_document.filename %></td>
                            <td><%= @document.user_document.created_at.strftime("%-d %b %Y %H:%M") %></td>
                            <td><%= file_size_verbose @document.user_document.byte_size %></td>
                            <td>
                                <%= link_to 'Download', @document.user_document, download: '' %>
                            </td>
                        </tr>     
                    </tbody>
                </table>
            <% end %>
        </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bstack Box</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">
      <%= link_to(root_path) do %>
        <b class="navbar-brand">Bstack Box</b>
      <% end %>
      <div class="navbar-right">
        <% if current_user %> 
          <%= link_to current_user.full_name, '/profile'  %>
          <%= link_to "Log out", logout_path, method: "delete" %>
        <% else %> 
          <%= link_to "Login", 'login' %>
          <%= link_to "Sign Up", 'signup' %>
        <% end %> 
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<div class="signup-form">
    <%= form_for(@user, url: user_path, method: 'patch') do |f| %>
		<h2>Edit Profile - <%= @user.user_name %></h2>
		<hr>
        <div class="form-group">
            <%= f.label :full_name, 'Full Name', class: "#{'text-danger' if @user.errors[:full_name].any?}" %>
            <%= f.text_field :full_name, class: "form-control #{'is-invalid' if @user.errors[:full_name].any?}", 
                required: true %>
            <% if @user.errors[:full_name].any? %>
                <small class="text-danger">
                    <%= @user.errors[:full_name][0] %>
                </small> 
            <% end %>  
        </div>
        <div class="form-group">
            <%= f.label :email, 'Email Address', class: "#{'text-danger' if @user.errors[:email].any?}" %>
            <%= f.email_field :email, class: "form-control #{'is-invalid' if @user.errors[:email].any?}", 
                required: true %>
            <% if @user.errors[:email].any? %>
                <small class="text-danger">
                    <%= @user.errors[:email][0] %>
                </small> 
            <% end %>  
        </div>
		<div class="form-group">
            <%= f.submit "Save", class: 'btn btn-primary btn-block btn-lg' %>
        </div>
    <% end %>
</div>

app/views/users/new.html.erb
<div class="signup-form">
    <%= form_for(@user, url: '/signup', method: 'post') do |f| %>
		<h2>Sign Up</h2>
		<hr>
        <div class="form-group">
            <%= f.label :user_name, 'Username', class: "#{'text-danger' if @user.errors[:user_name].any?}" %>
            <%= f.text_field :user_name, class: "form-control #{'is-invalid' if @user.errors[:user_name].any?}", 
                required: true, maxlength: 15 %>
            <% if @user.errors[:user_name].any? %>
                <small class="text-danger">
                    <%= @user.errors[:user_name][0] %>
                </small> 
            <% end %>  
        </div>
        <div class="form-group">
            <%= f.label :full_name, 'Name', class: "#{'text-danger' if @user.errors[:full_name].any?}" %>
            <%= f.text_field :full_name, class: "form-control #{'is-invalid' if @user.errors[:full_name].any?}", 
                required: true %>
            <% if @user.errors[:full_name].any? %>
                <small class="text-danger">
                    <%= @user.errors[:full_name][0] %>
                </small> 
            <% end %>
        </div>
        <div class="form-group">
            <%= f.label :email, 'Email', class: "#{'text-danger' if @user.errors[:email].any?}" %>
            <%= f.email_field :email, class: "form-control #{'is-invalid' if @user.errors[:email].any?}", 
                required: true %>
            <% if @user.errors[:email].any? %>
                <small class="text-danger">
                    <%= @user.errors[:email][0] %>
                </small> 
            <% end %>
        </div>
		<div class="form-group">
            <%= f.label :password, 'Password', class: "#{'text-danger' if @user.errors[:password].any?}" %>
            <%= f.password_field :password, 
                class: "form-control #{'is-invalid' if @user.errors[:password].any?}", 
                required: true, minlength: 8, maxlength: 15,
                pattern: '(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).*',
                title: 'Password must be atleast 8 characters long, contain atleast one uppercase, one lowercase and a number'
            %>
            <% if @user.errors[:password].any? %>
                <small class="text-danger">
                    <%= @user.errors[:password][0] %>
                </small> 
            <% end %>
        </div>
		<div class="form-group">
            <%= f.submit "Sign Up", class: 'btn btn-primary btn-block btn-lg' %>
        </div>
    <% end %>
	<div class="text-center">Have an account? <%= link_to "Click here to login", 'login' %></div>
</div>

app/views/users/show.html.erb
<div class="signup-form">
    <form>
    <h2><%= @user.user_name %> 's Profile</h2>
		<hr>
        <div class="form-group">
			<label>Complete Name</label>
            <input type="text" class="form-control" disabled value="<%= @user.full_name %>">
        </div>
        <div class="form-group">
			<label>Email Address</label>
        	<input type="text" class="form-control" disabled value="<%= @user.email %>">
        </div>
		<div class="form-group">
            <%= link_to '/profile/edit' do %>
                <button class="btn btn-primary btn-block btn-lg">
                    Edit Your Profile
                </button>
            <% end %>
        </div>
        <% if @profile_updated %> 
            <div class="form-message">
                <small class="text-success">Profile Updated Successfully!</small>
            </div>
        <% end %>
    </form>
</div>